### ISSUE TITLE
py.test freezes and errors 

### ISSUE THREAD

**Issue by ArcTanSusan** [cablehead/python-consul#111]
https://gist.github.com/anonymous/a406b6172e7cf3bc984f1ad5d9b9f935 shows the error output when running the full pytest unit test suite.

**Comment by abn** [comment]
@ArcTanSusan this could be an environmental issuem and the test is just waiting for consul to show up. Looking at the logs; it seems you're running under vagrant; this could be an issue since the test suite expects consul to be started and bound to a random port as part of the test environment setup. It could be that you have to configure your vagrant environment such that it allows this behavior.

**Comment by ArcTanSusan** [comment]
Yes, you are correct, the python-consul requires a running local consul server. 🎆
