### ISSUE TITLE
Install python-consul on python v2.7.9

### ISSUE THREAD

**Issue by zmkhp** [cablehead/python-consul#123]
When I insall python-consul on python v2.7.9,it shows:
      File "C:\Python27\Lib\site-packages\consul\aio.py", line 41
        resp = yield from aiohttp.request(method, uri,
                        ^
    SyntaxError: invalid syntax

I check that the aiohttp library is not installed.When I install aiohttp,it shows:
  raise RuntimeError("aiohttp requires Python 3.4.1+")

RunttimeError: aiohttp requires Python 3.4.1+

I have two questions:
1、Python-consul must run with python v3.4.1?
2、If the aiohttp is not installed,Python-consul can run normally?

Thanks!

**Comment by chrigl** [comment]
python-consul does not require python 3.4+. It works fine here on python 2.7.12

There is some part in setup.py to remove aio.py if asyncio is not available. This seems not to be run on your system.
https://github.com/cablehead/python-consul/blob/master/setup.py#L27
On my linux system "pip install python-consul" does not include aio.py

Anyway. It is save to remove C:\Python27\Lib\site-packages\consul\aio.py, and python-consul may work.

**Comment by ardling** [comment]
Just delete file "C:\Python27\Lib\site-packages\consul\aio.py". setup.py works badly in some cases, in linux too.

**Comment by zmkhp** [comment]
@chrigl  Thank you! I'm so sorry about replying too late.
I try this way,but It can't work still.Like @ardling 's words,It exists other cases.

**Comment by cablehead** [comment]
Could this be related to #118 ?

**Comment by abn** [comment]
@cablehead I am guessing the root cause here is that `asyncio` was already installed in the python2 environment and the [setup.py check](https://github.com/cablehead/python-consul/blob/master/setup.py#L26-L34) skips the deletion of `aio.py` module. The `aio.py` module will not work with python2 and hence will fail if imported.

We need to do one of the following;
1. add a conditional logic to wrap the whole module
2. improve the check in `setup.py` to remove if PY3
3. move the aio module to a new project `python-consul-aio`

Thoughts?
