### ISSUE TITLE
deregister service id and check id

### ISSUE THREAD

**Issue by chinakevinguo** [cablehead/python-consul#175]
Is this code really like this? when change 'get' to 'put' ,it works...
```python
            def deregister(self, service_id):
                """
                Used to remove a service from the local agent. The agent will
                take care of deregistering the service with the Catalog. If
                there is an associated check, that is also deregistered.
                """
                # return self.agent.http.get(
                #     CB.bool(), '/v1/agent/service/deregister/%s' % service_id)

                return self.agent.http.put(
                    CB.bool(), '/v1/agent/service/deregister/%s' % service_id)
```

**Comment by bobh66** [comment]
See PR #174

**Comment by bobh66** [comment]
I don't know when the above PR will be accepted, so if you need a workaround you can do something like this:

from consul import Consul
from consul.base import CB


class MyAgentService(Consul.Agent.Service):
    def deregister(self, service_id):
        return self.agent.http.put(CB.bool(), '/v1/agent/service/deregister/%s' % service_id)


consul = Consul(host=host, port=port)
consul.agent.service = MyAgentService(consul)

This will override the "bad" deregister method and use put instead of get.

**Comment by chinakevinguo** [comment]
ok, thanks ,i'll close this issue
