### ISSUE TITLE
Project and maintainer status.

### ISSUE THREAD

**Issue by eliasbrange** [cablehead/python-consul#210]
Howdy.

We are using `python-consul` heavily in our environment to interact with our consul cluster and we are getting ready to upgrade to consul 1.x.x. PR https://github.com/cablehead/python-consul/pull/182 seems to address this but it has been lying around for more than 6 months.

So, @abn and @cablehead, how is the development status on the project? Is it dead? At this state we are considering forking or finding another client.

**Comment by cablehead** [comment]
We are actively looking for additional maintainers. If you come across this and have time, interest, and ideally, use python-consul actively at work, please leave a message!

**Comment by beardedeagle** [comment]
Let me check with work if I can take over in some capacity

**Comment by matusvalo** [comment]
@cablehead I think I can help.

**Comment by cablehead** [comment]
@matusvalo Is it possible to shoot me an email? (my email address should be on my GitHub profile)

**Comment by asteven** [comment]
We also use python-consul at work.
I'm in the same position as @eliasbrange.
Willing to scratch my own itches and push upstream if you take it.

May I ask why https://groups.google.com/forum/#!forum/python-consul and https://groups.google.com/forum/#!forum/python-consul-admin require login for reading?
I usually don't use my google account. Would hate to login just to read a forum. Posting is something different of course.

**Comment by cablehead** [comment]
@asteven no reason. I think I've just changed it so anyone can now read messages (there aren't any :))

I've also deleted the `python-consul-admin` list. It'll be progress to just get one email list going.

**Comment by asteven** [comment]
I wonder if it would make sense to join forces with consulate. It seems there is a very large overlap in functionality. The main difference I see from a quick look is that python-consul supports asyncio, tornado, twisted and friends. But if this is the only difference, would it make sense to contribute implementations for that to consulate instead of struggling to maintain 2 projects?

I know it is somewhat blasphemous to mention this in your issue tracker.

**Comment by cablehead** [comment]
Not remotely blasphemous. We aren't guilds :)

> supports asyncio, tornado, twisted and friends. But if this is the only difference, [...]

>> All right... all right... but apart from better sanitation and medicine and education and irrigation and public health and roads and a freshwater system and baths and public order... what have the Romans done for us?

I think you've caught the core difference there. To handle async, you kinda need to plan for it from the start.

Consulate was actually around before python-consul. I haven't track it's development over the years, so things may have change, but this was why I started this module at the time:

https://groups.google.com/d/msg/consul-tool/lUVdUeo5eEM/-mH0qhNUrqQJ

One of the reasons Consulate has such a nice API for exposing Consul's key / value store as a python dict is (at least at the time) it didn't concern itself with async networking. It wasn't possible at the time to even get the index of the previous read, so you could then long poll for changes since that index.

The goal of python-consul is to expose simply and conveniently the _full_ capabilities of Consul's API. It's agnostic to usage after that. I'm hoping that makes it easy to then layer convenience layers for particular use cases on top.

Honestly though, what python-consul does is so simple if you do have a narrow use case, you could probably roll the part python-consul does you in half an afternoon. And I think that's calculation that's worthwhile making for projects.

**Comment by cablehead** [comment]
I'm looking to push a new release to pypi tomorrow afternoon with #190 and #218 

Shout out if you'd like to squeeze anything else in! Particularly handling breaking changes from Consul.

**Comment by asteven** [comment]
Well I have a unbiased interest in #217  :-)

But it probably needs some more eyes and possibly work to ensure it doesn't break anything.
Comments would be much appreciated.

**Comment by amuhametov** [comment]
@cablehead hi, what about maintainership?

**Comment by abarbare** [comment]
Hey @cablehead, I'm also using this lib actively and I think I may help to maintain and review some PRs. 
Do you still need help?

**Comment by hampsterx** [comment]
@cablehead this project is great, need to get those PR's merged :)

**Comment by and-semakin** [comment]
I guess we should go to a maintained fork with the most number of stars: https://github.com/poppyred/python-consul2
