### ISSUE TITLE
following redirects

### ISSUE THREAD

**Issue by hoffoo** [cablehead/python-consul#63]
Is it feasible for this lib to follow http redirects (either by default or optional)? This is required in our environment and doesn't seem hard to add.

Thanks!

**Comment by abn** [comment]
@hoffoo since requests is used under the hood, this should by default allow for redirects.

From the [requests documentation](http://docs.python-requests.org/en/latest/user/quickstart/#redirection-and-history):
> By default Requests will perform location redirection for all verbs except HEAD.

The only reason to add an optional parameter to the HTTPClient would be if you require redirects to be disallowed.

**Comment by abn** [comment]
Assuming this is resolved; closing. Feel free to re-open if required.
